Add introductory blog post about OES structure and governance
ContributorCovenant/ethicalsource pull request #98
Opened 2021-05-01 10:46 UTC by tobie

2021-05-01 20:50 UTC, CoralineAda commented on content/blog/how-we-work
> +As you know, the Ethical Source movement [organized into a legal entity](/blog/oes-announcement/) in late January.
I would take out the "As you know", and maybe move this sentence to the first paragraph

2021-05-01 20:51 UTC, CoralineAda approved these changes

2021-05-01 20:52 UTC, CoralineAda commented
@tobie Check out the deploy preview-- something's wrong with that page. https://deploy-preview-98--ethicalsource.netlify.app/blog/how-we-work

2021-05-01 20:53 UTC, CoralineAda requested changes
https://deploy-preview-98--ethicalsource.netlify.app/blog/how-we-work is not rendering, I'll take a look.

2021-05-01 20:56 UTC, CoralineAda commented
@tobie Just missing the `.md` extension on that file, then it should be good.

2021-05-02 13:19 UTC, tobie commented
> @tobie Just missing the `.md` extension on that file, then it should be good.

🤦‍♂️

2021-05-02 18:11 UTC, CoralineAda approved these changes

2021-05-02 18:11 UTC, CoralineAda commented
Looks great!

2021-05-02 18:11 UTC, merged